# Generated by Django 5.0 on 2024-01-06 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='city',
        ),
        migrations.AlterField(
            model_name='truck',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truck.sell_truck'),
        ),
    ]
