# Generated by Django 5.0 on 2023-12-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=250)),
                ('brand', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Motorcycle_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=250)),
                ('brand', models.CharField(max_length=250)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sell_Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=250)),
                ('model', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
                ('operation', models.CharField(max_length=250)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(upload_to='')),
                ('city', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sell Motorcycle',
            },
        ),
    ]
