# Generated by Django 5.0 on 2024-01-02 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorcycle',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='motorcycle',
            name='city',
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorcycle.sell_motorcycle'),
        ),
    ]
